IA_project_manager/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from IA_project_manager import settings
# import xadmin
from users import views


urlpatterns = [
    # path('xadmin/', xadmin.site.urls),
    path('admin/',admin.site.urls),
    # path('captcha/',include('captcha.urls')),
    path('' , views.index , name='index'),
    ##media配置——配合settings中的MEDIA_ROOT的配置，就可以在浏览器的地址栏访问media文件夹及里面的文件了
    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    path('users/', include(('users.urls', "users"), namespace="users")),
    path('plans/', include(('plans.urls', "plans"), namespace="plans")),
    path('ex/', include(('ex.urls', "ex"), namespace="ex")),
    path('exaudit/', include(('exaudit.urls', "exaudit"), namespace="exaudit")),
]


handler404 = views.handler_404
handler500 = views.handler_500

apps/ex/urls.py
# from django.contrib import admin
from django.urls import path, re_path
from .views import schedule_list, add_schedule, schedule_del, schedule_file, schedule_file_del, schedule_detail, \
    fix_schedule, problem_list, problem_detail, problem_add, auto_problem_class, add_problem
from .views import fix_problem, add_problem_file, del_problem_file, report_detail, add_feedback_file, del_feedback_file,re_finish_project
from .views import notice_info, add_report_file,del_report_file,clean_doubts,re_project,off_project,re_problem,re_feedback,add_feedback,del_feedback,re_feedback_file,re_feedback_file_del
from .views import re_problem_exportxl
urlpatterns = [
    re_path('schedule_list/(\d+)', schedule_list, name='schedule_list'),
    path('add_schedule', add_schedule, name='add_schedule'),
    path('schedule_del', schedule_del, name='schedule_del'),
    path('schedule_file', schedule_file, name='schedule_file'),
    path('schedule_file_del', schedule_file_del, name='schedule_file_del'),
    re_path('schedule_detail/(\d+)', schedule_detail, name='schedule_detail'),
    path('fix_schedule', fix_schedule, name='fix_schedule'),
    re_path('problem_list/(\d+)', problem_list, name='problem_list'),
    re_path('problem_detail/(\d+)', problem_detail, name='problem_detail'),
    re_path('problem_add/(\d+)', problem_add, name='problem_add'),
    path('auto_problem_class', auto_problem_class, name='auto_problem_class'),
    path('add_problem', add_problem, name='add_problem'),
    path('fix_problem', fix_problem, name='fix_problem'),
    # re_path('user_changeitems/(\d+)', user_changeitems, name='user_changeitems'),
    path('add_problem_file', add_problem_file, name='add_problem_file'),
    path('del_problem_file', del_problem_file, name='del_problem_file'),
    re_path('report_detail/(\d+)', report_detail, name='report_detail'),
    path('add_feedback_file', add_feedback_file, name='add_feedback_file'),
    path('del_feedback_file', del_feedback_file, name='del_feedback_file'),
    path('noitce_info', notice_info, name='notice_info'),
    path('add_report_file', add_report_file, name='add_report_file'),
    path('del_report_file', del_report_file, name='del_report_file'),
    path('clean_doubts', clean_doubts, name='clean_doubts'),
    path('off_project', off_project, name='off_project'),
    path('re_project', re_project, name='re_project'),
    re_path('re_problem/(\d+)', re_problem, name='re_problem'),
    re_path('re_feedback/(\d+)', re_feedback, name='re_feedback'),
    path('add_feedback', add_feedback, name='add_feedback'),
    path('del_feedback', del_feedback, name='del_feedback'),
    path('re_feedback_file', re_feedback_file, name='re_feedback_file'),
    path('re_feedback_file_del', re_feedback_file_del, name='re_feedback_file_del'),
    path('re_finish_project', re_finish_project, name='re_finish_project'),
    re_path('re_problem_exportxl/(\d+)', re_problem_exportxl, name='re_problem_exportxl'),
]

# handler404 = 'users.views.handler_404'
# handler500 = 'users.views.handler_500'

apps/ex/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from users.models import CompanyInifo, UserProfile
from plans.models import AuditCompanyInfo, PlansInifo,AllNoticeInfo


# Create your models here.
# 创建审计计划库
class ScheduleInifo(models.Model):
    company_id = models.ForeignKey(CompanyInifo, verbose_name='审计单位', on_delete=models.CASCADE,
                                   related_name='company_name11', null=True, blank=True)
    audit_company = models.ForeignKey(AuditCompanyInfo, verbose_name='被审计单位名称', on_delete=models.CASCADE, null=True,
                                      blank=True)
    username = models.ForeignKey(UserProfile, verbose_name='审计人员姓名', on_delete=models.CASCADE, null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    project_name = models.ForeignKey(PlansInifo, verbose_name='审计项目名称', on_delete=models.CASCADE, null=True, blank=True)
    schedule_title = models.CharField(max_length=50, verbose_name='任务名称', null=True, blank=True)
    schedule_content = models.TextField(verbose_name='任务内容', null=True, blank=True)
    schedule_feedback = models.TextField(verbose_name='任务反馈', null=True, blank=True)
    start_time = models.DateField(default=datetime.now, verbose_name='任务开始时间')
    end_time = models.DateField(default=datetime.now, verbose_name='任务结束时间')
    status = models.BooleanField(default=True, verbose_name="逻辑删除")

    def __str__(self):
        return self.schedule_title

    def coding(self):
        from users.tests import coding
        coding=coding(self.id)
        return coding

    class Meta:
        verbose_name = '任务详情'
        verbose_name_plural = verbose_name


class ProblemInfo(models.Model):
    company_id = models.ForeignKey(CompanyInifo, verbose_name='审计单位', on_delete=models.CASCADE,
                                   related_name='company_name12', null=True, blank=True)
    audit_company = models.ForeignKey(AuditCompanyInfo, verbose_name='被审计单位名称', on_delete=models.CASCADE, null=True,
                                      blank=True)
    username = models.ForeignKey(UserProfile, verbose_name='审计人员姓名', on_delete=models.CASCADE, null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    project_name = models.ForeignKey(PlansInifo, verbose_name='审计项目名称', on_delete=models.CASCADE, null=True, blank=True)
    status = models.BooleanField(default=True, verbose_name="逻辑删除")
    problem_title = models.CharField(max_length=50, verbose_name='问题名称', null=True, blank=True)
    problem_content = models.TextField(verbose_name='问题内容', null=True, blank=True)
    problem_feedback = models.TextField(verbose_name='问题反馈', null=True, blank=True)
    problem_type = models.CharField(max_length=10, verbose_name='问题类型', choices=(('sg', '建议'), ('re', '整改')),
                                    default='sg')
    problem_class = models.CharField(max_length=20, verbose_name='问题分类', null=True, blank=True)
    problem_status = models.CharField(max_length=10, verbose_name='问题状态',
                                      choices=(('do', '疑点'), ('el', '消除'), ('co', '确认')), default='do')

    def __str__(self):
        return self.problem_title

    def coding(self):
        from users.tests import coding
        coding=coding(self.id)
        return coding

    class Meta:
        verbose_name = '问题详情'
        verbose_name_plural = verbose_name


class ScheduleFileInifo(models.Model):
    company_id = models.ForeignKey(CompanyInifo, verbose_name='审计单位', on_delete=models.CASCADE,
                                   related_name='company_name13', null=True, blank=True)
    audit_company = models.ForeignKey(AuditCompanyInfo, verbose_name='被审计单位名称', on_delete=models.CASCADE, null=True,
                                      blank=True)
    username = models.ForeignKey(UserProfile, verbose_name='审计人员姓名', on_delete=models.CASCADE, null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    project_name = models.ForeignKey(PlansInifo, verbose_name='审计项目名称', on_delete=models.CASCADE, null=True, blank=True)
    status = models.BooleanField(default=True, verbose_name="逻辑删除")
    schedule_file = models.FileField(upload_to='plans/schedule/%Y/%m', max_length=100, verbose_name="记录文件", null=True,
                                     blank=True)

    def __str__(self):
        return self.project_name.project_name

    class Meta:
        verbose_name = '项目附件'
        verbose_name_plural = verbose_name


class ProblemFileInifo(models.Model):
    company_id = models.ForeignKey(CompanyInifo, verbose_name='审计单位', on_delete=models.CASCADE,
                                   related_name='company_name14', null=True, blank=True)
    audit_company = models.ForeignKey(AuditCompanyInfo, verbose_name='被审计单位名称', on_delete=models.CASCADE, null=True,
                                      blank=True)
    username = models.ForeignKey(UserProfile, verbose_name='审计人员姓名', on_delete=models.CASCADE, null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    project_name = models.ForeignKey(PlansInifo, verbose_name='审计项目名称', on_delete=models.CASCADE, null=True, blank=True)
    status = models.BooleanField(default=True, verbose_name="逻辑删除")
    problem_file = models.FileField(upload_to='plans/problem/%Y/%m', max_length=100, verbose_name="问题文件", null=True,
                                    blank=True)
    problem_id = models.ForeignKey(ProblemInfo, verbose_name='问题编号', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.project_name.project_name

    class Meta:
        verbose_name = '问题附件'
        verbose_name_plural = verbose_name


class ReportFileInifo(models.Model):
    company_id = models.ForeignKey(CompanyInifo, verbose_name='审计单位', on_delete=models.CASCADE,
                                   related_name='company_name15', null=True, blank=True)
    username = models.ForeignKey(UserProfile, verbose_name='审计人员姓名', on_delete=models.CASCADE, null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    project_name = models.ForeignKey(PlansInifo, verbose_name='审计项目名称', on_delete=models.CASCADE, null=True, blank=True)
    status = models.BooleanField(default=True, verbose_name="逻辑删除")
    report_file = models.FileField(upload_to='plans/report/%Y/%m', max_length=100, verbose_name="问题文件", null=True,
                                   blank=True)
    report_type = models.CharField(max_length=10, verbose_name='报告类型',
                                   choices=(('fi', '报告终稿'), ('fifi', '终稿附件'), ('pr', '报告过程稿'), ('prfi', '过程稿附件')),
                                   default='pr')

    def __str__(self):
        return self.project_name.project_name

    def coding(self):
        from users.tests import coding
        coding=coding(self.id)
        return coding

    class Meta:
        verbose_name = '报告附件'
        verbose_name_plural = verbose_name


class FeedbackFileInifo(models.Model):
    company_id = models.ForeignKey(CompanyInifo, verbose_name='审计单位', on_delete=models.CASCADE,
                                   related_name='company_name16', null=True, blank=True)
    username = models.ForeignKey(UserProfile, verbose_name='审计人员姓名', on_delete=models.CASCADE, null=True,
                                 blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    project_name = models.ForeignKey(PlansInifo, verbose_name='审计项目名称', on_delete=models.CASCADE, null=True,
                                     blank=True)
    status = models.BooleanField(default=True, verbose_name="逻辑删除")
    feedback_file = models.FileField(upload_to='plans/feedback/%Y/%m', max_length=100, verbose_name="征求意见附件", null=True,
                                     blank=True)
    feedback_type = models.CharField(max_length=10, verbose_name='过程类型', choices=(('se', '征求'), ('fe', '反馈')),
                                     default='se')

    def __str__(self):
        return self.project_name.project_name

    def coding(self):
        from users.tests import coding
        coding=coding(self.id)
        return coding

    class Meta:
        verbose_name = '征求意见'
        verbose_name_plural = verbose_name


class RectificationPrjectInfo(models.Model):
    project_name = models.ForeignKey(PlansInifo, verbose_name='审计项目名称', on_delete=models.CASCADE, null=True,
                                     blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    re_status= models.CharField(max_length=10, verbose_name='整改状态', choices=(('pr', '整改中'), ('co', '整改完成')),
                                     default='pr')
    company_id = models.ForeignKey(CompanyInifo, verbose_name='审计单位', on_delete=models.CASCADE,
                                   related_name='company_name19', null=True, blank=True)
    re_year=models.CharField(max_length=5,verbose_name='年度',default=str(datetime.now().year))
    status = models.BooleanField(default=True, verbose_name="逻辑删除")
    report_NO=models.ForeignKey(AllNoticeInfo, verbose_name='报告编号', on_delete=models.CASCADE,
                                   related_name='report_No', null=True, blank=True)

    def __str__(self):
        return self.project_name.project_name

    class Meta:
        verbose_name = '整改项目'
        verbose_name_plural = verbose_name

class RectificationProblemInfo(models.Model):
    re_problem=models.ForeignKey(ProblemInfo, verbose_name='整改问题', on_delete=models.CASCADE,
                                   related_name='problem_info', null=True, blank=True)
    re_project=models.ForeignKey(RectificationPrjectInfo, verbose_name='整改项目', on_delete=models.CASCADE,
                                   related_name='re_project', null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

templates/ex/re_project.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 整改追踪列表 {% endblock %}

{% block content-wrapper %}
    <div class="content-wrapper">
        <div class="content">
            <div class="breadcrumb-wrapper">


            </div>
            <!-- First Row  -->
            <div class="row">
                <div class="col-lg-12">

                    <div class="card card-default">
                        <div class="card-header card-header-border-bottom">
                            <h2>整改项目列表</h2>
                        </div>
                        <div class="card-body">
                            <div class="row ">
                                <div class="col-sm-2">
                                    <ul class="nav nav-tabs nav-stacked flex-column">
                                        <li class="nav-item">
                                            <a href="#vtab1" class="nav-link active" data-toggle="tab"
                                               aria-expanded="true">
                                                <i class="mdi mdi-feather"></i> 整改追踪项目</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="#vtab2" class="nav-link" data-toggle="tab" aria-expanded="false">
                                                <i class="mdi mdi-lock"></i> 整改完成项目</a>
                                        </li>

                                    </ul>
                                </div>
                                <div class="tab-content col-sm-10 ">
                                    <div class="tab-pane fade active show" id="vtab1" aria-expanded="true">
                                            <div class="card-body">
                                            <table id="responsive-data-table" class="table dt-responsive nowrap"
                                                   style="width:100%">
                                                <thead>
                                                <tr>
                                                    <th>序号</th>
                                                    <th>项目名称</th>
                                                    <th>年度</th>
                                                    <th>状态</th>
                                                    <th>报告编号</th>
                                                    <th>报告名称</th>
                                                </tr>
                                                </thead>

                                                <tbody>
                                                {% for re_project in re_pr_project %}
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td><a href="{% url 'ex:re_problem' re_project.id %}">{{ re_project.project_name.project_name }}</a></td>
                                                    <td>{{ re_project.re_year }}</td>
                                                    <td>{{ re_project.get_re_status_display }}</td>
                                                    <td>{{ re_project.report_NO.notice_NO }}</td>
                                                    <td>{{ re_project.report_NO.notice_name }}</td>
                                                </tr>
                                                 {% endfor %}
                                                </tbody>

                                            </table>
                                            </div>

                                    </div>
                                    <div class="tab-pane fade" id="vtab2" aria-expanded="false">
                                        <div class="card-body">
                                            <table id="responsive-data-table2" class="table dt-responsive nowrap"
                                                   style="width:100%">
                                                <thead>
                                                <tr>
                                                    <th>序号</th>
                                                    <th>项目名称</th>
                                                    <th>年度</th>
                                                    <th>状态</th>
                                                    <th>报告编号</th>
                                                    <th>报告名称</th>
                                                </tr>
                                                </thead>

                                                <tbody>
                                                {% for re_project in re_fi_project %}
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td><a href="{% url 'ex:re_problem' re_project.id %}">{{ re_project.project_name.project_name }}</a></td>
                                                    <td>{{ re_project.re_year }}</td>
                                                    <td>{{ re_project.get_re_status_display }}</td>
                                                    <td>{{ re_project.report_NO.notice_NO }}</td>
                                                    <td>{{ re_project.report_NO.notice_name }}</td>
                                                </tr>
                                                 {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>

{% endblock %}

{% block myjs %}
    <pre class="mt-4">
    <script src="{% static 'assets/plugins/data-tables/jquery.datatables.min.js' %}"></script>
    <script src="{% static 'assets/plugins/data-tables/datatables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'assets/plugins/data-tables/datatables.responsive.min.js' %}"></script>
    <link href="{% static 'assets/plugins/data-tables/datatables.bootstrap4.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/plugins/data-tables/responsive.datatables.min.css' %}" rel="stylesheet">
{#    <link href=""https://unpkg.com/sleek-dashboard/dist/assets/css/sleek.min.css">#}
    </pre>
    <script>
        jQuery(document).ready(function () {
            jQuery('#responsive-data-table').DataTable({
                "aLengthMenu": [[20, 30, 50, 75, -1], [20, 30, 50, 75, "All"]],
                "pageLength": 30,
                "dom": '<"row justify-content-between top-information"lf>rt<"row justify-content-between bottom-information"ip><"clear">'
            });
        });
        jQuery(document).ready(function () {
            jQuery('#responsive-data-table2').DataTable({
                "aLengthMenu": [[20, 30, 50, 75, -1], [20, 30, 50, 75, "All"]],
                "pageLength": 30,
                "dom": '<"row justify-content-between top-information"lf>rt<"row justify-content-between bottom-information"ip><"clear">'
            });
        });
    </script>

{% endblock %}