IA_project_manager/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from IA_project_manager import settings
# import xadmin
from users import views


urlpatterns = [
    # path('xadmin/', xadmin.site.urls),
    path('admin/',admin.site.urls),
    # path('captcha/',include('captcha.urls')),
    path('' , views.index , name='index'),
    ##media配置——配合settings中的MEDIA_ROOT的配置，就可以在浏览器的地址栏访问media文件夹及里面的文件了
    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    path('users/', include(('users.urls', "users"), namespace="users")),
    path('plans/', include(('plans.urls', "plans"), namespace="plans")),
    path('ex/', include(('ex.urls', "ex"), namespace="ex")),
    path('exaudit/', include(('exaudit.urls', "exaudit"), namespace="exaudit")),
]


handler404 = views.handler_404
handler500 = views.handler_500

apps/exaudit/urls.py
# from django.contrib import admin
from django.urls import path, re_path
from .views import exaudit_feedback,exaudit_return,add_feedback,del_feedback,re_feedback_file,re_feedback_file_del,start_detail,start_detail1,notice_info,notice_file,notice_del,start_info,start_file,start_file_del,audit_company_info,audit_company_del
from .views import schedule_list,add_schedule,schedule_detail,schedule_del,schedule_file,schedule_file_del,fix_schedule,problem_list,problem_add,auto_problem_class,add_problem,problem_detail,fix_problem,add_problem_file,del_problem_file
from .views import report_detail,add_feedback_file,del_feedback_file,notice_info1,add_report_file,del_report_file,clean_doubts
urlpatterns = [

    path('exaudit_feedback', exaudit_feedback, name='exaudit_feedback'),
    path('exaudit_return', exaudit_return, name='exaudit_return'),
    path('add_feedback', add_feedback, name='add_feedback'),
    path('del_feedback', del_feedback, name='del_feedback'),
    path('re_feedback_file', re_feedback_file, name='re_feedback_file'),
    path('re_feedback_file_del', re_feedback_file_del, name='re_feedback_file_del'),
    path('start_detail', start_detail, name='start_detail'),
    re_path('start_detail1/(\w+)', start_detail1, name='start_detail1'),
    path('notice_info', notice_info, name='notice_info'),
    path('notice_file', notice_file, name='notice_file'),
    path('notice_del', notice_del, name='notice_del'),
    path('start_info', start_info, name='start_info'),
    path('start_file', start_file, name='start_file'),
    path('start_file_del', start_file_del, name='start_file_del'),
    path('audit_company_info', audit_company_info, name='audit_company_info'),
    path('audit_company_del', audit_company_del, name='audit_company_del'),
    re_path('schedule_list/(\d+)', schedule_list, name='schedule_list'),
    path('add_schedule', add_schedule, name='add_schedule'),
    re_path('schedule_detail/(\d+)', schedule_detail, name='schedule_detail'),
    path('schedule_del', schedule_del, name='schedule_del'),
    path('schedule_file', schedule_file, name='schedule_file'),
    path('schedule_file_del', schedule_file_del, name='schedule_file_del'),
    path('fix_schedule', fix_schedule, name='fix_schedule'),
    re_path('problem_list/(\d+)', problem_list, name='problem_list'),
    re_path('problem_add/(\d+)', problem_add, name='problem_add'),
    path('auto_problem_class', auto_problem_class, name='auto_problem_class'),
    path('add_problem', add_problem, name='add_problem'),
    re_path('problem_detail/(\d+)', problem_detail, name='problem_detail'),
    path('fix_problem', fix_problem, name='fix_problem'),
    path('add_problem_file', add_problem_file, name='add_problem_file'),
    path('del_problem_file', del_problem_file, name='del_problem_file'),
    re_path('report_detail/(\d+)', report_detail, name='report_detail'),
    path('add_feedback_file', add_feedback_file, name='add_feedback_file'),
    path('del_feedback_file', del_feedback_file, name='del_feedback_file'),
    path('notice_info1', notice_info1, name='notice_info1'),
    path('add_report_file', add_report_file, name='add_report_file'),
    path('del_report_file', del_report_file, name='del_report_file'),
    path('clean_doubts', clean_doubts, name='clean_doubts'),
    # re_path('user_changeitems/(\d+)', user_changeitems, name='user_changeitems'),

]

# handler404 = 'users.views.handler_404'
# handler500 = 'users.views.handler_500'

apps/exaudit/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from users.models import CompanyInifo, UserProfile
from plans.models import AuditCompanyInfo, PlansInifo,AllNoticeInfo

apps/exaudit/forms.py
from django import forms
from .models import PlansInifo

apps/exaudit/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
# from django.db.models import Count,Sum
from django.db.models.aggregates import Aggregate, Count, Sum
# Create your views here.
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from plans.forms import PlanAddInfoForm
from ex.models import ScheduleInifo, ProblemInfo, ScheduleFileInifo, ProblemFileInifo, FeedbackFileInifo, ReportFileInifo
from ex.models import RectificationPrjectInfo,RectificationProblemInfo,RectificationFeedbackInfo,RectificationFeedbackFileInfo
from plans.models import PlansInifo, AuditMemberInfo, AuditCompanyInfo, AllNoticeInfo,StartFieldInfo,StartInfo,AllNoticeFileInfo
from users.models import UserProfile
from django.db.models import Q
import os
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout, login
import datetime
from django.core.files import File
from users.tests import coding,uncoding


def exaudit_return(request):
    return render(request,'exaudit/exaudit_return.html',{})

def exaudit_feedback(request):
    if request.method=='POST':
        re_problem_id=uncoding(request.POST.get('re_problem_id'))
        if re_problem_id == '0':
            return render(request, 'exaudit/exaudit_return.html', {
                're_problem_msg':'编码错误'
            })
        else:
            re_problem = RectificationProblemInfo.objects.filter(status=True, id=int(re_problem_id)).first()
            re_project = RectificationPrjectInfo.objects.filter(status=True,id=re_problem.re_project_id,re_status='pr').first()
            if re_project:
                re_feedback_list = RectificationFeedbackInfo.objects.filter(status=True,re_project_name_id=re_problem_id).order_by('-add_time')
                re_feedback_nm = list(set(re_feedback.id for re_feedback in re_feedback_list))
                today = datetime.datetime.now().today()
                re_feedback_file_list = RectificationFeedbackFileInfo.objects.filter(status=True, re_feedback_id__in=re_feedback_nm)
                return render(request,'exaudit/exaudit_feedback.html',{
                    're_project':re_project,
                    # 're_project_id':re_project_id,
                    're_problem':re_problem,
                    're_feedback_list':re_feedback_list,
                    'today':today,
                    're_feedback_file_list':re_feedback_file_list,
                    're_problem_id':coding(re_problem_id)
                })
            else:
                return render(request, 'exaudit/exaudit_return.html', {
                    're_problem_msg':'项目已整改结束'
                })

def add_feedback(request):
    if request.method == "POST":
        re_department=request.POST.get('re_department')
        re_person=request.POST.get('re_person')
        re_improve=request.POST.get('re_improve')
        re_date=request.POST.get('re_date')
        re_situation=request.POST.get('re_situation')
        accountability_is=request.POST.get('accountability_is')
        accountability_content=request.POST.get('accountability_content')
        announcement_is=request.POST.get('announcement_is')
        remarks=request.POST.get('remarks')
        re_problem_id=int(uncoding(request.POST.get('re_problem_id')))
        re_problem = RectificationProblemInfo.objects.filter(status=True, id=re_problem_id).first()
        re_project = RectificationPrjectInfo.objects.filter(status=True, id=re_problem.re_project_id,
                                                            re_status='pr').first()
        try:
            a=RectificationFeedbackInfo()
            a.re_project_name_id=re_problem_id
            a.company_id_id=re_project.company_id_id
            a.re_improve=re_improve
            a.re_department=re_department
            a.re_person=re_person
            a.re_date=datetime.datetime.strptime(re_date,'%Y-%m-%d')
            a.re_situation=re_situation
            a.accountability_is=accountability_is
            a.accountability_content=accountability_content
            a.announcement_is=announcement_is
            a.remarks=remarks
            a.save()
            re_problem=RectificationProblemInfo.objects.filter(status=True,id=int(re_problem_id))
            b=re_problem[0]
            b.re_improve=re_improve
            b.re_department = re_department
            b.re_person = re_person
            b.re_date = datetime.datetime.strptime(re_date, '%Y-%m-%d')
            b.re_situation = re_situation
            b.accountability_is = accountability_is
            b.accountability_content = accountability_content
            b.announcement_is = announcement_is
            b.remarks = remarks
            b.username_id=None
            b.save()
            return JsonResponse({'status': 'ok', 'msg': '添加成功'})
        except Exception as e:
            return JsonResponse({'status': 'false', 'msg': '添加失败'})

def del_feedback(request):
    feedback_id = request.GET.get('feedback_id')
    feedback_list1 = RectificationFeedbackInfo.objects.filter(status=True, id=int(feedback_id))
    feedback_info = feedback_list1[0]
    try:
        problem_info_id=feedback_info.re_project_name_id
        a = feedback_info
        a.status = False
        a.save()
        feedback_info2=RectificationFeedbackInfo.objects.filter(status=True,re_project_name_id=problem_info_id).order_by('-add_time').first()
        problem_info=RectificationProblemInfo.objects.filter(status=True,id=problem_info_id).first()
        if feedback_info2:
            b=problem_info
            b.re_improve=feedback_info2.re_improve
            b.re_department=feedback_info2.re_department
            b.re_person=feedback_info2.re_person
            b.re_date=feedback_info2.re_date
            b.re_situation=feedback_info2.re_situation
            b.accountability_is=feedback_info2.accountability_is
            b.accountability_content=feedback_info2.accountability_content
            b.announcement_is=feedback_info2.announcement_is
            b.remarks=feedback_info2.remarks
            b.username_id=feedback_info2.username_id
            b.save()
        else:
            b=problem_info
            b.re_improve=None
            b.re_department=None
            b.re_person=None
            b.re_date=datetime.datetime.today()
            b.re_situation='pr'
            b.accountability_is='n'
            b.accountability_content=None
            b.announcement_is='n'
            b.remarks=None
            b.username_id=None
            b.save()
        return JsonResponse({'status': 'ok', 'msg': '删除成功'})
    except Exception as e:
        return JsonResponse({'status': 'false', 'msg': '删除失败'})


def re_feedback_file(request):
    re_problem_id = int(uncoding(request.POST.get('re_problem_id')))
    re_problem = RectificationProblemInfo.objects.filter(status=True, id=re_problem_id).first()
    re_feedback_id = request.POST.get('re_feedback_id')
    re_feedback_file = request.FILES.get('re_feedback_file')
    try:
        a=RectificationFeedbackFileInfo()
        a.company_id_id=re_problem.company_id_id
        a.re_feedback_id=int(re_feedback_id)
        a.re_file=re_feedback_file
        a.save()
        return JsonResponse({'status': 'ok', 'msg': '新增成功'})
    except Exception as e:
        return JsonResponse({'status': 'false', 'msg': '新增失败'})

def re_feedback_file_del(request):
    re_feedback_file_id = request.GET.get('re_feedback_file_id')
    re_feedback_file_list1 = RectificationFeedbackFileInfo.objects.filter(status=True, id=int(re_feedback_file_id))
    re_feedback_file = re_feedback_file_list1[0]
    try:
        a = re_feedback_file
        a.status = False
        a.save()
        return JsonResponse({'status': 'ok', 'msg': '删除成功'})
    except Exception as e:
        return JsonResponse({'status': 'false', 'msg': '删除失败'})



def start_detail(request):
    if request.method == "POST":
        switch = 'open'
    # switch_stauts = PlansInifo.objects.filter(status=True, id=int(project_id), project_status='cp').first()
    # if switch_stauts:
    #     switch = 'close'
        project_id=uncoding(request.POST.get('project_id'))
        project = PlansInifo.objects.filter(status=True, id=int(project_id),project_exaudit=True,project_status='ex').first()
        if project_id == '0':
            return render(request, 'exaudit/exaudit_return.html', {
                'project_msg':'编码错误'
            })
        elif not project :
            return render(request, 'exaudit/exaudit_return.html', {
                'project_msg':'非外审项目'
            })
        else:

            notice_info = AllNoticeInfo.objects.filter(status=True, company_id_id=project.company_id_id,
                                                       project_name_id=int(project_id), notice_type='audit').first()
            if notice_info:
                notice_id_1 = notice_info.id
                notice_file = AllNoticeFileInfo.objects.filter(status=True, notice_name_id=int(notice_id_1))
            else:
                notice_file = ''

            start_detail = StartInfo.objects.filter(status=True, company_id=project.company_id_id,
                                                    project_name=int(project_id)).first()
            start_file = StartFieldInfo.objects.filter(status=True, project_name=int(project_id))

            audit_company = AuditCompanyInfo.objects.filter(status=True, project_name_id=int(project_id))
            project_member = AuditMemberInfo.objects.filter(status=True, project_name_id=int(project_id))
            member_list_id = list(set(member.username.id for member in project_member))

            user_list = UserProfile.objects.filter(is_active='1', company_name=project.company_id_id)
            except_member_list = list(set(member.id for member in user_list))

templates/exaudit/exaudit_return.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="description"
              content="Sleek Dashboard - Free Bootstrap 4 Admin Dashboard Template and UI Kit. It is very powerful bootstrap admin dashboard, which allows you to build products like admin panels, content management systems and CRMs etc.">


        <title>Return</title>

        <!-- PLUGINS CSS STYLE -->
        <link href="{% static 'assets/plugins/nprogress/nprogress.css' %}" rel="stylesheet"/>


        <!-- SLEEK CSS -->
        <link id="sleek-css" rel="stylesheet" href="{% static 'assets/css/sleek.css' %}"/>

        <!-- FAVICON -->
        <link href="{% static 'assets/img/favicon.png' %}" rel="shortcut icon"/>


        <script src="{% static 'assets/plugins/nprogress/nprogress.js' %}"></script>
    </head>

</head>
<body class="" id="body">
<div class="container d-flex flex-column justify-content-between vh-100">
    <div class="row justify-content-center mt-5">
        <div class="col-xl-5 col-lg-6 col-md-10">
            <div class="card">
                <div class="card-header bg-primary">
                    <div class="app-brand">
                        <a href="#">
                            <svg class="brand-icon" xmlns="#" preserveAspectRatio="xMidYMid"
                                 width="30" height="33"
                                 viewBox="0 0 30 33">
                                <g fill="none" fill-rule="evenodd">
                                    <path class="logo-fill-blue" fill="#7DBCFF" d="M0 4v25l8 4V0zM22 4v25l8 4V0z"/>
                                    <path class="logo-fill-white" fill="#FFF" d="M11 4v25l8 4V0z"/>
                                </g>
                            </svg>
                            <span class="brand-name">编码跳转</span>
                        </a>
                    </div>
                </div>
                <div class="card-body p-5">

                    <h4 class="text-dark mb-5">请输入整改问题编码</h4>
                    <form action="{% url 'exaudit:exaudit_feedback' %}" method="post" autocomplete="off">
                        {% csrf_token %}
                        <div class="row">
                            <div class="form-group col-md-12 mb-4">
                                <input type="txt" class="form-control input-lg" id="email"
                                       aria-describedby="emailHelp" placeholder="问题加密数字编码" name="re_problem_id">
                            </div>
                            <button type="submit" class="btn btn-lg btn-success btn-block mb-4">提交</button>
                            <span class="text-center badge badge-warning">{{ re_problem_msg }}</span>
                        </div>
                    </form>
                </div>

                <div class="card-body p-5">

                    <h4 class="text-dark mb-5">请输入项目编码</h4>
                    <form action="{% url 'exaudit:start_detail' %}" method="post" autocomplete="off">
                        {% csrf_token %}
                        <div class="row">
                            <div class="form-group col-md-12 mb-4">
                                <input type="txt" class="form-control input-lg" id="email"
                                       aria-describedby="emailHelp" placeholder="项目加密数字编码" name="project_id">
                            </div>
                            <button type="submit" class="btn btn-lg btn-info btn-block mb-4">提交</button>
                            <span class="text-center badge badge-warning">{{ project_msg }}</span>

                        </div>
                    </form>

                </div>

                <div class="card-body pl-5">
                        <div class="row">
                            <p><font size="4" color="white"> </font></p>
                            <p class="justify-content-center" ><font size="4" color="#dc143c"><a  href="/">
                                返回首页</a></font>
                            </p>
                        </div>
                    </div>
            </div>
        </div>
    </div>
    <div class="copyright pl-0">
        <p class="text-center">&copy; 2020 内审项目管理系统
            <a class="text-primary" href="mailto:redgysun_impa@163.com" target="_blank">Redgysun</a>.
        </p>
    </div>
</div>

</body>
</html>