IA_project_manager/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from IA_project_manager import settings
# import xadmin
from users import views


urlpatterns = [
    # path('xadmin/', xadmin.site.urls),
    path('admin/',admin.site.urls),
    # path('captcha/',include('captcha.urls')),
    path('' , views.index , name='index'),
    ##media配置——配合settings中的MEDIA_ROOT的配置，就可以在浏览器的地址栏访问media文件夹及里面的文件了
    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    path('users/', include(('users.urls', "users"), namespace="users")),
    path('plans/', include(('plans.urls', "plans"), namespace="plans")),
    path('ex/', include(('ex.urls', "ex"), namespace="ex")),
    path('exaudit/', include(('exaudit.urls', "exaudit"), namespace="exaudit")),
]


handler404 = views.handler_404
handler500 = views.handler_500

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime

# Create your models here.
#创建审计单位库
class CompanyInifo(models.Model):
    company_name = models.CharField(max_length=50,verbose_name='审计单位名称')
    company_code = models.CharField(max_length=20,verbose_name='组织机构代码证号')
    company_department= models.CharField(max_length=20,verbose_name='审计单位部门名称')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    def __str__(self):
        return self.company_name

    class Meta:
        verbose_name = '审计单位名称'
        verbose_name_plural =verbose_name


# 创建审计用户库
class UserProfile(AbstractUser):
    company_name = models.ForeignKey(CompanyInifo,verbose_name='审计单位', on_delete=models.CASCADE,related_name='company_name1',default='1')
    user_image = models.ImageField(upload_to='users/image/%Y/%m',max_length=100,verbose_name="用户头像",null=True,blank=True,default='users/image/u6.jpg')
    user_PQ = models.CharField(max_length=100, verbose_name='职业资格',null=True, blank=True )
    user_phone=models.CharField(max_length=11, verbose_name='手机', null=True, blank=True)
    user_gender = models.CharField(max_length=10, choices=(('male', '男'), ('female', '女')), default='male', verbose_name='性别')
    user_birthday = models.DateField(verbose_name='生日', null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')
    leftbar_title=models.CharField(max_length=30,verbose_name="标题布局",default="HeaderL_Fix")
    leftbar_option=models.CharField(max_length=30,verbose_name="边栏布局",default="sidebar-static-minified")
    leftbar_titlecolor=models.CharField(max_length=30,verbose_name="标题背景",default="HeaderB_Light")
    leftbar_navcolor=models.CharField(max_length=30,verbose_name="导航背景",default="Sidebar2_Dark")
    leftbar_navposition=models.CharField(max_length=30,verbose_name="导航位置",default="Siderbar2_Left")


    def __str__(self):
        return self.username

    def project_num(self):
        from plans.models import AuditMemberInfo
        now_year=datetime.today().year
        project_num=AuditMemberInfo.objects.filter(status=True,add_time__year=now_year,username_id=self.id)
        return  project_num

    def lvl1_num(self):
        from plans.models import AuditMemberInfo
        now_year=datetime.today().year
        lvl1_num=AuditMemberInfo.objects.filter(status=True,add_time__year=now_year,username_id=self.id,audit_role='lvl1')
        return  lvl1_num

    def going_num(self):
        from plans.models import AuditMemberInfo,PlansInifo
        now_year=datetime.today().year
        ex_project_list=PlansInifo.objects.filter(status=True,company_id_id=self.company_name_id,project_status='ex')
        ex=list(set(ex_project.id for ex_project in ex_project_list))
        going_num=AuditMemberInfo.objects.filter(status=True,add_time__year=now_year,username_id=self.id,project_name_id__in=ex)
        return  going_num


    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}首页{% endblock %}

{% block search_form %}

{% endblock %}
{% block content-wrapper %}
    <div class="content-wrapper">
        <div class="content">
            <div class="breadcrumb-wrapper d-flex align-items-center justify-content-between">

             </div>

            <div class="row">
                <div class="col-xl-2">
                    <div class="card card-default mb-4 mb-lg-5">
                        <div class="card-header card-header-border-bottom">
                            <h2><font size="3">日期</font></h2>
                        </div>

                        <div class="card-body p-4 py-xl-6 px-xl-2">
                            <div class="circle circle-lg"
                                 data-size="200"
                                 data-value="0.83"
                                 data-thickness="20"
                                 data-fill="{
														&quot;color&quot;: &quot;#35D00E&quot;
													}"
                            >
                                <div class="circle-content justify-content-start">
                                    <h6 class="text-uppercase text-dark font-weight-bold"><font size="4"> {{ now_date|date:'Y-m-d' }}  星期{% if now_date.isoweekday == 1 %}一{% elif now_date.isoweekday == 2 %}二
                                    {% elif now_date.isoweekday == 3 %}三{% elif now_date.isoweekday == 4 %}四{% elif now_date.isoweekday == 5 %}五{% elif now_date.isoweekday == 6 %}六{% elif now_date.isoweekday == 7 %}日{% endif %}</font></h6>

                                    <strong></strong>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2">
                    <div class="card card-default mb-4 mb-lg-5">
                        <div class="card-header card-header-border-bottom">
                            <h2><font size="3">本年项目总数</font></h2>
                        </div>

                        <div class="card-body p-4 py-xl-6 px-xl-2">
                            <div class="circle circle-lg"
                                 data-size="200"
                                 data-value="0.83"
                                 data-thickness="20"
                                 data-fill="{
														&quot;color&quot;: &quot;#35D00E&quot;
													}"
                            >
                                <div class="circle-content">
                                    <h6 class="text-uppercase text-dark font-weight-bold"><font size="6">{{ project_total_num.count }}</font></h6>

                                    <strong></strong>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2">
                    <div class="card card-default mb-4 mb-lg-5">
                        <div class="card-header card-header-border-bottom">
                            <h2><font size="3">执行中项目数</font></h2>
                        </div>

                        <div class="card-body p-4 py-xl-6 px-xl-2">
                            <div class="circle circle-lg"
                                 data-size="200"
                                 data-value="0.83"
                                 data-thickness="20"
                                 data-fill="{
														&quot;color&quot;: &quot;#35D00E&quot;
													}"
                            >
                                <div class="circle-content">
                                    <h6 class="text-uppercase text-dark font-weight-bold"><font size="6">{{ project_ex_num.count }}</font></h6>

                                    <strong></strong>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2">
                    <div class="card card-default mb-4 mb-lg-5">
                        <div class="card-header card-header-border-bottom">
                            <h2><font size="3">总未执行计划数</font></h2>
                        </div>

                        <div class="card-body p-4 py-xl-6 px-xl-2">
                            <div class="circle circle-lg"
                                 data-size="200"
                                 data-value="0.83"
                                 data-thickness="20"
                                 data-fill="{
														&quot;color&quot;: &quot;#35D00E&quot;
													}"
                            >
                                <div class="circle-content">
                                    <h6 class="text-uppercase text-dark font-weight-bold"><font size="6">{{ project_un_num.count }}</font></h6>

                                    <strong></strong>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2">
                    <div class="card card-default mb-4 mb-lg-5">
                        <div class="card-header card-header-border-bottom">
                            <h2><font size="3">持续整改项目</font></h2>
                        </div>

                        <div class="card-body p-4 py-xl-6 px-xl-2">
                            <div class="circle circle-lg"
                                 data-size="200"
                                 data-value="0.83"
                                 data-thickness="20"
                                 data-fill="{
														&quot;color&quot;: &quot;#35D00E&quot;
													}"
                            >
                                <div class="circle-content">
                                    <h6 class="text-uppercase text-dark font-weight-bold"><font size="6">{{ re_project_num.count }}</font></h6>

                                    <strong></strong>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2">
                    <div class="card card-default mb-4 mb-lg-5">
                        <div class="card-header card-header-border-bottom">
                            <h2><font size="2">日常通知数--{{ now_date.year }}年</font></h2>
                        </div>

                        <div class="card-body p-4 py-xl-6 px-xl-2">
                            <div class="circle circle-lg"
                                 data-size="200"
                                 data-value="0.83"
                                 data-thickness="20"
                                 data-fill="{
														&quot;color&quot;: &quot;#35D00E&quot;
													}"
                            >
                                <div class="circle-content">
                                    <h6 class="text-uppercase text-dark font-weight-bold"><font size="6">{{ normal_notice_num.count }}</font></h6>

                                    <strong></strong>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>



            </div>

            <div class="row">
                {% for user in user_list %}
                <div class="col-lg-6 col-xl-4 col-xxl-3">
                    <div class="card card-default mt-6 mb-4">
                        <div class="card-body text-center p-4">
                                <div class="image mb-3 mt-n9">
                                    <img src="{{ MEDIA_URL }}{{ user.user_image }}" class="img-fluid rounded-circle"
                                         alt="Avatar Image">
                                </div>

                                <h5 class="card-title text-dark">{{ user.first_name }}</h5>

                                <ul class="list-unstyled">
                                    <li class="d-flex mb-1">
                                        <i class="mdi mdi-map mr-1"></i>
                                        <span>{{ user.get_user_gender_display }}</span>
                                    </li>
                                    <li class="d-flex mb-1">
                                        <i class="mdi mdi-email mr-1"></i>
                                        <span>{{ user.email }}</span>
                                    </li>
                                    <li class="d-flex mb-1">
                                        <i class="mdi mdi-phone mr-1"></i>
                                        <span>{% if user.user_phone %}{{ user.user_phone }}{% endif %}</span>
                                    </li>
                                </ul>
                            </a>

                            <p  class="card-text text-left mb-3"><font size="2">最近一次登陆时间：{{ user.last_login|date:'Y-m-d H:i:s' }}</font>  </p>

                            <div class="row justify-content-center">
                                <div class="col-4 px-1">
                                    <div class=" circle"
                                         data-size="120"
                                         data-value="0.95"
                                         data-thickness="4"
                                         data-fill="{
														&quot;color&quot;: &quot;#35D00E&quot;
													}"
                                    >
                                        <div class="circle-content">
                                            <h6 class="text-uppercase">本年项目数</h6>
                                            <h6>{{ user.project_num.count }}</h6>
                                            <strong></strong>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-4 px-1">
                                    <div class=" circle"
                                         data-size="120"
                                         data-value="0.65"
                                         data-thickness="4"
                                         data-fill="{
														&quot;color&quot;: &quot;#fec400&quot;
													}"
                                    >
                                        <div class="circle-content">
                                            <h6 class="text-uppercase">本年主审项目</h6>
                                            <h6>{{ user.lvl1_num.count }}</h6>
                                            <strong></strong>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-4 px-1">
                                    <div class=" circle"
                                         data-size="120"
                                         data-value="0.35"
                                         data-thickness="4"
                                         data-fill="{
														&quot;color&quot;: &quot;#fe5461&quot;
													}"
                                    >
                                        <div class="circle-content">
                                            <h6 class="text-uppercase">进行中项目</h6>
                                            <h6>{{ user.going_num.count }}</h6>
                                            <strong></strong>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}


            </div>



        </div>


    </div>
{% endblock %}
{% block myjs %}



    <script>

    </script>
{% endblock %}