IA_project_manager/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from IA_project_manager import settings
# import xadmin
from users import views


urlpatterns = [
    # path('xadmin/', xadmin.site.urls),
    path('admin/',admin.site.urls),
    # path('captcha/',include('captcha.urls')),
    path('' , views.index , name='index'),
    ##media配置——配合settings中的MEDIA_ROOT的配置，就可以在浏览器的地址栏访问media文件夹及里面的文件了
    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    path('users/', include(('users.urls', "users"), namespace="users")),
    path('plans/', include(('plans.urls', "plans"), namespace="plans")),
    path('ex/', include(('ex.urls', "ex"), namespace="ex")),
    path('exaudit/', include(('exaudit.urls', "exaudit"), namespace="exaudit")),
]


handler404 = views.handler_404
handler500 = views.handler_500

apps/exaudit/urls.py
# from django.contrib import admin
from django.urls import path, re_path
from .views import exaudit_feedback,exaudit_return,add_feedback,del_feedback,re_feedback_file,re_feedback_file_del,start_detail,start_detail1,notice_info,notice_file,notice_del,start_info,start_file,start_file_del,audit_company_info,audit_company_del
from .views import schedule_list,add_schedule,schedule_detail,schedule_del,schedule_file,schedule_file_del,fix_schedule,problem_list,problem_add,auto_problem_class,add_problem,problem_detail,fix_problem,add_problem_file,del_problem_file
from .views import report_detail,add_feedback_file,del_feedback_file,notice_info1,add_report_file,del_report_file,clean_doubts
urlpatterns = [

    path('exaudit_feedback', exaudit_feedback, name='exaudit_feedback'),
    path('exaudit_return', exaudit_return, name='exaudit_return'),
    path('add_feedback', add_feedback, name='add_feedback'),
    path('del_feedback', del_feedback, name='del_feedback'),
    path('re_feedback_file', re_feedback_file, name='re_feedback_file'),
    path('re_feedback_file_del', re_feedback_file_del, name='re_feedback_file_del'),
    path('start_detail', start_detail, name='start_detail'),
    re_path('start_detail1/(\w+)', start_detail1, name='start_detail1'),
    path('notice_info', notice_info, name='notice_info'),
    path('notice_file', notice_file, name='notice_file'),
    path('notice_del', notice_del, name='notice_del'),
    path('start_info', start_info, name='start_info'),
    path('start_file', start_file, name='start_file'),
    path('start_file_del', start_file_del, name='start_file_del'),
    path('audit_company_info', audit_company_info, name='audit_company_info'),
    path('audit_company_del', audit_company_del, name='audit_company_del'),
    re_path('schedule_list/(\d+)', schedule_list, name='schedule_list'),
    path('add_schedule', add_schedule, name='add_schedule'),
    re_path('schedule_detail/(\d+)', schedule_detail, name='schedule_detail'),
    path('schedule_del', schedule_del, name='schedule_del'),
    path('schedule_file', schedule_file, name='schedule_file'),
    path('schedule_file_del', schedule_file_del, name='schedule_file_del'),
    path('fix_schedule', fix_schedule, name='fix_schedule'),
    re_path('problem_list/(\d+)', problem_list, name='problem_list'),
    re_path('problem_add/(\d+)', problem_add, name='problem_add'),
    path('auto_problem_class', auto_problem_class, name='auto_problem_class'),
    path('add_problem', add_problem, name='add_problem'),
    re_path('problem_detail/(\d+)', problem_detail, name='problem_detail'),
    path('fix_problem', fix_problem, name='fix_problem'),
    path('add_problem_file', add_problem_file, name='add_problem_file'),
    path('del_problem_file', del_problem_file, name='del_problem_file'),
    re_path('report_detail/(\d+)', report_detail, name='report_detail'),
    path('add_feedback_file', add_feedback_file, name='add_feedback_file'),
    path('del_feedback_file', del_feedback_file, name='del_feedback_file'),
    path('notice_info1', notice_info1, name='notice_info1'),
    path('add_report_file', add_report_file, name='add_report_file'),
    path('del_report_file', del_report_file, name='del_report_file'),
    path('clean_doubts', clean_doubts, name='clean_doubts'),
    # re_path('user_changeitems/(\d+)', user_changeitems, name='user_changeitems'),

]

# handler404 = 'users.views.handler_404'
# handler500 = 'users.views.handler_500'

apps/users/urls.py
# from django.contrib import admin
from django.urls import path,re_path
from .views import user_login, user_logout, user_register, user_setting,user_changepassword,user_changeitems,users_list
from .views import user_fixinfo,user_changeimage

urlpatterns = [
    path('user_login/', user_login, name='user_login'),
    path('user_logout', user_logout, name='user_logout'),
    path('user_register', user_register, name='user_register'),
    path('user_setting/', user_setting, name='user_setting'),
    path('user_changepassword', user_changepassword, name='user_changepassword'),
    path('users_list/', users_list, name='users_list'),
    re_path('user_changeitems/(\d+)', user_changeitems, name='user_changeitems'),
    path('user_changeimage/', user_changeimage, name='user_changeimage'),
    path('user_fixinfo/', user_fixinfo, name='user_fixinfo'),
]

# handler404 = 'users.views.handler_404'
# handler500 = 'users.views.handler_500'

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime

# Create your models here.
#创建审计单位库
class CompanyInifo(models.Model):
    company_name = models.CharField(max_length=50,verbose_name='审计单位名称')
    company_code = models.CharField(max_length=20,verbose_name='组织机构代码证号')
    company_department= models.CharField(max_length=20,verbose_name='审计单位部门名称')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    def __str__(self):
        return self.company_name

    class Meta:
        verbose_name = '审计单位名称'
        verbose_name_plural =verbose_name


# 创建审计用户库
class UserProfile(AbstractUser):
    company_name = models.ForeignKey(CompanyInifo,verbose_name='审计单位', on_delete=models.CASCADE,related_name='company_name1',default='1')
    user_image = models.ImageField(upload_to='users/image/%Y/%m',max_length=100,verbose_name="用户头像",null=True,blank=True,default='users/image/u6.jpg')
    user_PQ = models.CharField(max_length=100, verbose_name='职业资格',null=True, blank=True )
    user_phone=models.CharField(max_length=11, verbose_name='手机', null=True, blank=True)
    user_gender = models.CharField(max_length=10, choices=(('male', '男'), ('female', '女')), default='male', verbose_name='性别')
    user_birthday = models.DateField(verbose_name='生日', null=True, blank=True)
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')
    leftbar_title=models.CharField(max_length=30,verbose_name="标题布局",default="HeaderL_Fix")
    leftbar_option=models.CharField(max_length=30,verbose_name="边栏布局",default="sidebar-static-minified")
    leftbar_titlecolor=models.CharField(max_length=30,verbose_name="标题背景",default="HeaderB_Light")
    leftbar_navcolor=models.CharField(max_length=30,verbose_name="导航背景",default="Sidebar2_Dark")
    leftbar_navposition=models.CharField(max_length=30,verbose_name="导航位置",default="Siderbar2_Left")


    def __str__(self):
        return self.username

    def project_num(self):
        from plans.models import AuditMemberInfo
        now_year=datetime.today().year
        project_num=AuditMemberInfo.objects.filter(status=True,add_time__year=now_year,username_id=self.id)
        return  project_num

    def lvl1_num(self):
        from plans.models import AuditMemberInfo
        now_year=datetime.today().year
        lvl1_num=AuditMemberInfo.objects.filter(status=True,add_time__year=now_year,username_id=self.id,audit_role='lvl1')
        return  lvl1_num

    def going_num(self):
        from plans.models import AuditMemberInfo,PlansInifo
        now_year=datetime.today().year
        ex_project_list=PlansInifo.objects.filter(status=True,company_id_id=self.company_name_id,project_status='ex')
        ex=list(set(ex_project.id for ex_project in ex_project_list))
        going_num=AuditMemberInfo.objects.filter(status=True,add_time__year=now_year,username_id=self.id,project_name_id__in=ex)
        return  going_num


    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

apps/users/forms.py
from django import forms
from .models import UserProfile

class UserLoginForm(forms.Form):
    username = forms.EmailField(required=True)
    password = forms.CharField(required=True,min_length=8,max_length=20,error_messages={
        'required':'密码必须填写',
        'min_length':'密码至少8位',
        'max_length':'密码不能超过20位'
    })

class UserRegisterForm(forms.Form):
    username = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=8, max_length=20, error_messages={
        'required': '密码必须填写',
        'min_length': '密码至少8位',
        'max_length': '密码不能超过20位'
    })


class UserChangePasswordForm(forms.Form):
    password = forms.CharField(required=True,min_length=8,max_length=20,error_messages={
        'required':'密码必须填写',
        'min_length':'密码至少8位',
        'max_length':'密码不能超过20位'
    })
    password1 = forms.CharField(required=True,min_length=8,max_length=20,error_messages={
        'required':'密码必须填写',
        'min_length':'密码至少8位',
        'max_length':'密码不能超过20位'
    })


# class UserChangeImageForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ['user_image']

class UserChangeInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['first_name', 'user_gender', 'user_phone','user_birthday', 'user_PQ']

templates/users/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="description"
              content="Sleek Dashboard - Free Bootstrap 4 Admin Dashboard Template and UI Kit. It is very powerful bootstrap admin dashboard, which allows you to build products like admin panels, content management systems and CRMs etc.">


        <title>Login</title>

        <!-- PLUGINS CSS STYLE -->
        <link href="{% static 'assets/plugins/nprogress/nprogress.css' %}" rel="stylesheet"/>


        <!-- SLEEK CSS -->
        <link id="sleek-css" rel="stylesheet" href="{% static 'assets/css/sleek.css' %}"/>

        <!-- FAVICON -->
        <link href="{% static 'assets/img/favicon.png' %}" rel="shortcut icon"/>


        <script src="{% static 'assets/plugins/nprogress/nprogress.js' %}"></script>
    </head>

</head>
<body class="" id="body">
<div class="container d-flex flex-column justify-content-between vh-100">
    <div class="row justify-content-center mt-5">
        <div class="col-xl-5 col-lg-6 col-md-10">
            <div class="card">
                <div class="card-header bg-primary">
                    <div class="app-brand">
                        <a href="#">
                            <svg class="brand-icon" xmlns="#" preserveAspectRatio="xMidYMid"
                                 width="30" height="33"
                                 viewBox="0 0 30 33">
                                <g fill="none" fill-rule="evenodd">
                                    <path class="logo-fill-blue" fill="#7DBCFF" d="M0 4v25l8 4V0zM22 4v25l8 4V0z"/>
                                    <path class="logo-fill-white" fill="#FFF" d="M11 4v25l8 4V0z"/>
                                </g>
                            </svg>
                            <span class="brand-name">内审项管系统登录</span>
                        </a>
                    </div>
                </div>
                <div class="card-body p-5">

                    <h4 class="text-dark mb-5">请输入邮箱和密码</h4>
                    <form action="{% url 'users:user_login' %}" method="post" autocomplete="off">
                        {% csrf_token %}
                        <div class="row">
                            <div class="form-group col-md-12 mb-4">
                                <input type="email" class="form-control input-lg" id="email"
                                       aria-describedby="emailHelp" placeholder="邮箱" name="username">
                            </div>
                            <div class="form-group col-md-12 ">
                                <input type="password" class="form-control input-lg" id="password"
                                       placeholder="密码" name="password">
                            </div>
                            <button type="submit" class="btn btn-lg btn-primary btn-block mb-4">登录</button>
                            <span class="text-center badge badge-warning">{{ msg }}</span>
                            {% for key,err in user_login_form.errors.items %}
                                <span class="text-center badge badge-warning"> {{ err }}</span>
                            {% endfor %}
                            <p>请点击
                                <a class="text-blue" href="{% url 'users:user_register' %}">这里</a>注册新的账户！
                            </p>
                        </div>
                    </form>
                    <div class="card-body pl-5">
                        <div class="row">
                            <p><font size="4" color="white"> </font></p>
                            <p class="justify-content-center" ><font size="4" color="#dc143c"><a  href="{% url 'exaudit:exaudit_return' %}">
                                外部审计人员及整改反馈请从此处进入</a></font>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright pl-0">
        <p class="text-center">&copy; 2020 内审项目管理系统
            <a class="text-primary" href="mailto:redgysun_impa@163.com" target="_blank">Redgysun</a>.
        </p>
    </div>
</div>

</body>
</html>

templates/users/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="description"
              content="Sleek Dashboard - Free Bootstrap 4 Admin Dashboard Template and UI Kit. It is very powerful bootstrap admin dashboard, which allows you to build products like admin panels, content management systems and CRMs etc.">


        <title>Register</title>

        <base href="{% static '' %}"/>
        <link href="{% static 'assets/css/local.google.fonts.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/css/materialdesignicons.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/plugins/nprogress/nprogress.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/css/sleek.css' %}" rel="stylesheet" id="sleek-css"/>
        <link href="{% static 'assets/img/favicon.png' %}" rel="shortcut icon"/>
        <script src="{% static 'assets/plugins/nprogress/nprogress.js' %}"></script>
    </head>

</head>
<body class="" id="body">
<div class="container d-flex flex-column justify-content-between vh-100">
    <div class="row justify-content-center mt-5">
        <div class="col-xl-5 col-lg-6 col-md-10">
            <div class="card">
                <div class="card-header bg-primary">
                    <div class="app-brand">
                        <a href="#">
                            <svg class="brand-icon" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid"
                                 width="30"
                                 height="33" viewBox="0 0 30 33">
                                <g fill="none" fill-rule="evenodd">
                                    <path class="logo-fill-blue" fill="#7DBCFF" d="M0 4v25l8 4V0zM22 4v25l8 4V0z"/>
                                    <path class="logo-fill-white" fill="#FFF" d="M11 4v25l8 4V0z"/>
                                </g>
                            </svg>
                            <span class="brand-name">内审项管系统注册</span>
                        </a>
                    </div>
                </div>
                <div class="card-body p-5">
                    <h4 class="text-dark mb-5">请输入姓名、邮箱、密码</h4>
                    <form action="{% url 'users:user_register' %}" method="post" autocomplete="off">
                        {% csrf_token %}
                        <div class="row">
                            <div class="form-group col-md-12 mb-4">
                                <input type="text" class="form-control input-lg" id="name" aria-describedby="nameHelp"
                                       placeholder="姓名" name = "first_name">
                            </div>
                            <div class="form-group col-md-12 mb-4">
                                <input type="email" class="form-control input-lg" id="email"
                                       aria-describedby="emailHelp" placeholder="邮箱" name="username">
                            </div>
                            <div class="form-group col-md-12 ">
                                <input type="password" class="form-control input-lg" id="password"
                                       placeholder="密码" name = "password">
                            </div>
                            <div class="form-group col-md-12 ">
                                <input type="password" class="form-control input-lg" id="cpassword"
                                       placeholder="再次确认密码" name="password1">
                            </div>
                            <div class="col-md-12">
                                <div class="d-inline-block mr-3">
                                    <label class="control control-checkbox">
                                        <input type="checkbox" name="check" value="ok"/>
                                        <div class="control-indicator"></div>
                                        后续请尽快联系管理员确认账户所属单位。
                                    </label>

                                </div>
                                <button type="submit" class="btn btn-lg btn-primary btn-block mb-4">注册</button>
                                <div class="text-dark mb-5 text-center" id="jsLoginTips">
                                <span class="text-center badge badge-warning">{{ msg }}</span>
                            </div>
                                <p>您已经有账号的话请点击
                                    <a class="text-blue" href="{% url 'users:user_login' %}">这里</a>登陆
                                </p>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <div class="copyright pl-0">
        <p class="text-center">&copy; 2020 内审项目管理系统
            <a class="text-primary" href="#" target="_blank">Redgysun</a>.
        </p>
    </div>
</div>

</body>
</html>

templates/users/setting.html
{% extends "base.html" %}
{% load static %}
{% block title %} 个人信息设置{% endblock %}
{% block search_form %} {% endblock %}
{% block content-wrapper %}
    <div class="content-wrapper">
        <div class="content">
            <div class="bg-white border rounded">
                <div class="row no-gutters">
                    <div class="col-lg-4 col-xl-3">
                        <div class="profile-content-left pt-5 pb-3 px-3 px-xl-5">
                            <div class="card text-center widget-profile px-0 border-0">
                                <div class="card-img mx-auto rounded-circle">
                                    <img src="{{ MEDIA_URL }}{{ request.user.user_image }}" alt="user image">#}
                                </div>
                                <div class="card-body">
                                    <h4 class="py-2 text-dark">{{ request.user.first_name }}</h4>
                                    <p>{{ request.user.email }}</p>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between ">
                                <div class="text-center pb-4">
                                    <h6 class="text-dark pb-2">{{ project_num.count }}</h6>
                                    <p>总项目数</p>
                                </div>
                                <div class="text-center pb-4">
                                    <h6 class="text-dark pb-2">{{ usedays }}</h6>
                                    <p>已用天数</p>
                                </div>
                                <div class="text-center pb-4">
                                    <h6 class="text-dark pb-2">{{ request.user.add_time|date:"Y-m-d" }}</h6>
                                    <p>注册时间</p>
                                </div>
                            </div>
                            <hr class="w-100">
                            <div class="contact-info pt-4">
                                <h5 class="text-dark mb-1">相关信息</h5>
                                <p class="text-dark font-weight-medium pt-4 mb-2" hidden>性别</p>
                                <p hidden>{% if request.user.user_gender == 'male' %}男{% else %}女{% endif %}</p>
                                <p class="text-dark font-weight-medium pt-4 mb-2">电话</p>
                                <p>{{ request.user.user_phone }}</p>
                                <p class="text-dark font-weight-medium pt-4 mb-2">公司</p>
                                <p>{{ request.user.company_name.company_name }}</p>
                                <p class="text-dark font-weight-medium pt-4 mb-2">部门</p>
                                <p>{{ request.user.company_name.company_department }}</p>
                                <p class="text-dark font-weight-medium pt-4 mb-2">邮箱</p>
                                <p>{{ request.user.email }}</p>
                                <p class="text-dark font-weight-medium pt-4 mb-2">职称</p>
                                <p>{{ request.user.user_PQ }}</p>
                                <p class="text-dark font-weight-medium pt-4 mb-2" hidden>联系</p>
                                <p class="pb-3 social-button" hidden>
                                    <a href="#" class="mb-1 btn btn-outline btn-twitter rounded-circle">
                                        <i class="mdi mdi-twitter"></i>
                                    </a>
                                    <a href="#" class="mb-1 btn btn-outline btn-linkedin rounded-circle">
                                        <i class="mdi mdi-linkedin"></i>
                                    </a>
                                    <a href="#" class="mb-1 btn btn-outline btn-facebook rounded-circle">
                                        <i class="mdi mdi-facebook"></i>
                                    </a>
                                    <a href="#" class="mb-1 btn btn-outline btn-skype rounded-circle">
                                        <i class="mdi mdi-skype"></i>
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8 col-xl-9">
                        <div class="profile-content-right py-5">
                            <ul class="nav nav-tabs px-3 px-xl-5 nav-style-border" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="settings-tab" data-toggle="tab" href="#settings"
                                       role="tab" aria-controls="settings" aria-selected="false">个人信息设置</a>
                                </li>
                            </ul>
                            <div class="tab-content px-3 px-xl-5" id="myTabContent">
                                <div class="tab-pane fade show active" id="settings" role="tabpanel"
                                     aria-labelledby="settings-tab">
                                    <div class="mt-5">
                                        <div class="form-group row mb-6">

                                            <label for="coverImage"#}
                                                   class="col-sm-4 col-lg-2 col-form-label">用户头像</label>
                                            <div class="col-sm-8 col-lg-10">
                                                <div class="custom-file mb-1">
                                                    <form id="jsAvatarForm" enctype="multipart/form-data"
                                                          method="post"
                                                          action="{% url 'users:user_changeimage' %}"
                                                          enctype="multipart/form-data">
                                                        {% csrf_token %}
                                                        <input type="file" class="mb-1 btn btn-outline-secondary" id="coverImage"
                                                               name="image">
                                                        <input type="submit" class="mb-1 btn  disabled btn-primary">
                                                        </form>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                        <form method="post" action="{% url 'users:user_fixinfo' %}" enctype="multipart/form-data" onSubmit="javascript:return window.confirm('确认提交吗？')">
                                        {% csrf_token %}
                                        <div class="row mb-2">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label for="firstName">姓名</label>
                                                    <input type="text" class="form-control" id="first_name"
                                                          name="first_name" value="{{ request.user.first_name }}">
                                                </div>
                                            </div>

                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label class="text-dark mb-2 mt-4 font-weight-medium d-inline-block mr-3"
                                                           for="">性别</label>
                                                    <ul class="list-unstyled list-inline">
                                                        <li class="d-inline-block mr-3">
                                                            <label class="control control-radio">男
                                                                <input type="radio" name="user_gender" id="user_gender"
                                                                      value="male" {% if request.user.user_gender == 'male' %} checked="checked" {% endif %}/>
                                                                <div class="control-indicator"></div>
                                                            </label>
                                                        </li>
                                                        <li class="d-inline-block mr-3">
                                                            <label class="control control-radio">女
                                                                <input type="radio" {% if request.user.user_gender == 'female' %} checked="checked" {% endif %} name="user_gender" id="user_gender" value="female"/>
                                                                <div class="control-indicator"></div>
                                                            </label>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group mb-4">
                                            <label for="userName">电话（小于11位）</label>
                                            <input type="text" class="form-control" id="user_phone"  name="user_phone"
                                                   value="{{ request.user.user_phone }}">

                                        </div>

                                        <div class="form-group mb-4">
                                            <label for="date">生日</label>
                                            <input type="date" class="form-control" id="user_birthday" name="user_birthday"
                                                   value="{{ request.user.user_birthday|date:"Y-m-d" }}">
                                        </div>

                                        <div class="form-group mb-4">
                                            <label for="user_pq">职称(100字以内）</label>
                                            <input type="text" class="form-control" id="user_PQ" name="user_PQ"
                                                   value="{{ request.user.user_PQ }}">
                                        </div>

                                        <div class="d-flex justify-content-end mt-5">
                                            <button type="submit" class="btn btn-primary mb-2 btn-pill">提 交
                                            </button>
                                        </div>

                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}



{% block myjs %}

{% endblock %}